# This code is licensed from DallasO to the user under the MIT license.
# See LICENSE for details.
# https://github.com/DallasO/home-assistant-config-orb
version: 2.1

description: |
  An orb used to ensure your Home Assistant configuration is compatible with new releases https://www.home-assistant.io/
  This orb's source is available here:
  https://github.com/DallasO/home-assistant-config-orb

executors:
  hass:
    description: |
      This is a docker image that contains the specified home-assistant release
    parameters:
      tag:
        description: |
          This is the release you would like to test your configuration with
        type: enum
        default: stable
        enum: ["stable", "latest", "beta", "rc", "dev"]
    docker:
      - image: homeassistant/home-assistant:<< parameters.tag >>

commands:
  script-check-config:
    description: "A command to check the config file"
    steps:
      - checkout
      - run:
          name: Check Config
          command: |
            mv secrets.example.yaml secrets.yaml
            cd /usr/src/homeassistant
            python -m homeassistant -c ~/project/ \
            --script check_config

jobs:
  check-config:
    description: |
      Use home-assistant to check your config.
    executor: hass
    steps:
      - script-check-config

examples:
  check-config-workflow:
    description: |
      Checkout and run Home Assistants check-config script against your configuration

    usage:
      version: 2.1

      orbs:
        hass-config: DallasO/home-assistant-config@x.y.z

      workflows:
        hass-config:
          jobs:
            - hass-config/check-config

  custom-release:
    description: |
      Use a custom release

    usage:
      version: 2.1

      orbs:
        hass-config: DallasO/home-assistant-config@x.y.z

      workflows:
        hass-config:
          jobs:
            - hass-config/check-config:
                executor:
                  name: hass
                  tag: beta
