# This code is licensed from DallasO to the user under the MIT license.
# See LICENSE for details.
# https://github.com/DallasO/home-assistant-config-orb
description: |
      Checkout and run Home Assistants check-config script against your configuration

usage:
  version: 2.1

  orbs:
    hass-config: DallasO/home-assistant-config@x.y.z

  workflows:
    hass-config:
      jobs:
        - hass-config/check-config
