# This code is licensed from DallasO to the user under the MIT license.
# See LICENSE for details.
# https://github.com/DallasO/home-assistant-config-orb
description: |
      Use home-assistant to check your config.
executor: home-assistant
steps:
  - script-check-config
